### ISSUE TITLE
Unable to connect to bridge+/capsules

### ISSUE THREAD

**Issue by ProfessorKaos** [jonglissimo/Flowtoy-Connect-Bridge-OSC-Module#1]
Hi Jonglissimo,

I'm very happy to find this module here. I've got it installed, but I'm unable to set up the connection to my bridge+/capsules. I'm not sure what address to put in the 'remote host' and 'port' field. Or actually any of the other settings to get the system set up.

Using Chataigne v1.9.16
Flowtoys Bridge (official) is on and connected via Bluetooth to my Windows (10) PC.  I've been trying with a device bluetooth address of: fc:b1:ce:31:14:11

**Comment by manuelmitasch** [comment]
This module does not work with the "official" Flowtoys bridge. It only works with an advanced bridge that is based on an esp32 module that let it connect through WiFi.
